### ISSUE TITLE
Reason for exclusion of css-hyphens in Tachyons

### ISSUE THREAD

**Issue by nii236** [mrmrs/css-hyphens#1]
I just found out about the existence of this module.

It doesn't appear on the main Tachyons CSS website, nor does it come as part of the main minified file.

Is there a reason for this?

**Comment by mrmrs** [comment]
Hi @nii236,
I don't find it useful to have in core - and it isn't a part of the tachyons project at all. 
Hyphens don't work that well in my experience so I tend not to use them in css. 
If you find it useful, it should be fairly easy to add it to your own local build. Let me know if you have any questions on how to do that.
